from typing import Any, Dict, Optional, Protocol


class ShopifyPort(Protocol):
    async def find_product_id_by_handle(self, handle: str) -> Optional[str]: ...

    async def find_product_id_by_sku(self, sku: str) -> Optional[str]: ...

    async def create_product_from_input(self, product: Dict[str, Any]) -> Dict[str, Any]: ...

    async def update_product_from_input(self, product: Dict[str, Any]) -> Dict[str, Any]: ...
