from typing import Any, Dict, List, Optional, Protocol


class ShopifyPort(Protocol):
    async def get_product(self, gid: str) -> Dict[str, Any]: ...

    async def get_product_metafields(
        self, gid: str, identifiers: list[Dict[str, str]]
    ) -> list[Dict[str, Any]]: ...

    async def find_product_id_by_handle(self, handle: str) -> Optional[str]: ...

    async def find_product_id_by_sku(self, sku: str) -> Optional[str]: ...

    async def create_product_from_input(self, product: Dict[str, Any]) -> Dict[str, Any]: ...

    async def update_product_from_input(self, product: Dict[str, Any]) -> Dict[str, Any]: ...

    async def create_product_options(
        self, product_id: str, options: list[Dict[str, Any]]
    ) -> Dict[str, Any]: ...

    async def bulk_create_product_variants(
        self, product_id: str, variants: list[Dict[str, Any]]
    ) -> Dict[str, Any]: ...

    async def bulk_delete_product_variants(
        self, product_id: str, variant_ids: list[str]
    ) -> Dict[str, Any]: ...

    async def list_products_for_audit(
        self, query: Optional[str] = None, limit: int = 50
    ) -> list[Dict[str, Any]]: ...

    async def create_staged_upload(self) -> Dict[str, Any]: ...

    async def upload_to_staged_url(
        self, url: str, parameters: List[Dict[str, str]], jsonl_data: str
    ) -> None: ...

    async def run_bulk_mutation(self, staged_upload_path: str) -> Dict[str, Any]: ...

    async def get_bulk_operation(self, operation_id: str) -> Dict[str, Any]: ...

    async def wait_for_bulk_operation(
        self,
        operation_id: str,
        *,
        poll_interval: float = 5.0,
        timeout: float = 600.0,
    ) -> Dict[str, Any]: ...

    def build_product_set_jsonl(self, products: List[Dict[str, Any]]) -> str: ...
