from typing import Any, Protocol, Dict, List, Optional


class SupabasePort(Protocol):
    def save_file(self, file_id: str, name: str, content: bytes, content_type: str | None = None) -> None: ...

    def get_file(self, file_id: str) -> Optional[Dict[str, Any]]: ...

    def delete_file(self, file_id: str) -> bool: ...

    def save_file_thumbnail(self, *, file_id: str, content: bytes) -> str | None: ...

    def create_or_update_run(self, run_id: str, fields: Dict[str, Any]) -> None: ...

    def finalize_run(self, run_id: str, *, status: str, duration_ms: int | None = None, error: str | None = None, extra_fields: Dict[str, Any] | None = None) -> None: ...

    def get_product_draft(self, draft_id: str) -> Optional[Dict[str, Any]]: ...

    def save_product_draft(self, *, draft_id: str, run_id: str | None, import_mode: str, draft_name: str | None, input_file_id: str | None = None, input_filename: str | None = None, output_file_id: str | None = None, output_filename: str | None = None, products: List[Dict[str, Any]] = []) -> Dict[str, Any]: ...
