create table if not exists public.source_link_trace_events (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  attempt_id uuid,
  shop_domain text,
  run_id text,
  source_file_id text,
  highlight_file_id text,
  component text not null,
  stage text not null,
  status text not null default 'info',
  request_id text,
  correlation_id text,
  duration_ms integer,
  details jsonb not null default '{}'::jsonb
);

create index if not exists source_link_trace_events_attempt_idx
  on public.source_link_trace_events (attempt_id, created_at);
create index if not exists source_link_trace_events_shop_created_idx
  on public.source_link_trace_events (shop_domain, created_at desc);
create index if not exists source_link_trace_events_stage_status_idx
  on public.source_link_trace_events (stage, status, created_at desc);

alter table public.source_link_trace_events enable row level security;
revoke all on table public.source_link_trace_events from anon, authenticated;

comment on table public.source_link_trace_events is
  'Development-only, sanitized diagnostics for source-link viewer attempts.';
